### PR TITLE
Add xmldsig filter2 with version 2.0.27

### PR DESCRIPTION
**Pull request by hilleer**

### CODE REVIEW

**Comment by rmhrisk** [comment]
Curious, why close?

**Comment by hilleer** [comment]
@rmhrisk sorry, mistakenly opened here. This PR was supposed to be opened on our fork :)

**Comment by rmhrisk** [comment]
Do you envision submitting a PR in future to keep this project and your fork in sync?

**Comment by hilleer** [comment]
@rmhrisk yes, we will open a proper PR :)

**Comment by rmhrisk** [comment]
Great. Would hate to see a unnecessary fork persist forever :)

**Pull request closed without merging**
