### PR TITLE
Feature/move cert decode to xmldsig

### PR DESCRIPTION
**Pull request by Deepanjan66**

### CODE REVIEW

**Comment by Deepanjan66** [comment]
Accidentally created the pull request here instead of the forked repository. Please ignore. Thanks.

**Comment by rmhrisk** [comment]
Why was the custom class needed?

**Comment by Deepanjan66** [comment]
We have our own implementation of the x509Certificate class (including the mapping for different OID keys, logic for decoding the values, and a few, more specific, getters) which was built with asn1js and pkijs in a different project. We already use xmldsigjs for other things and are looking into moving over to the x509Certificate wrapper provided here. This custom class is more of a placeholder which will eventually contain code from our own implementation. I foresee this class morphing into the x509Certificate class that already exists in this project with a few extra methods added on top.

**Comment by rmhrisk** [comment]
OK.

We hate to see people fork the project unnecessarily or need to add functionality that belongs in the project into their own.

Do let us know if you see missing things.

We would love to hear about what you are doing with the project though?

**Comment by Deepanjan66** [comment]
Thanks for your question. We are an e-conveyancing platform based in Australia and one of our business requirements is to sign `documents` (in the form of xml payloads) for third party authorities we are connected with. We have been using fortify for this and it has helped us a lot so far.

As part of this process, we are required to support the “xmldsig-filter2” transform. This is the primary reason for us maintaining our own fork of `xmldsigjs`. Our implementation of this transform is very specific to our needs at its current stage and this is why we haven't started talks of a formal pull request yet. 

Please let me know if you are interested in starting a conversation in that regard. I am aware of an email thread from April that included my manager where this was discussed shortly. For reference, the subject of that email was "Fortify usage".

**Comment by rmhrisk** [comment]
Thanks for sharing, we really love to hear when the crazy things we built are used, especially when they are used to make real products. Though not a library per-se, you may be interested in our [Hancock](https://hancock.ink) product which verifies and creates cryptographically signed PDFs using the same approach (also all in JS).

We would love to see [XML Path Filter 2](https://www.w3.org/TR/xmldsig-filter2/) supported so please do create a PR.

**Comment by Deepanjan66** [comment]
Thank you, Ryan. I will attempt to spend a bit of time in the coming week or two to look at what's involved in getting our implementation to a PR ready state. I have noticed that there is an [issue](https://github.com/PeculiarVentures/xmldsigjs/issues/5#issue-198783879) for this exact feature request. Might continue further conversation there.

**Pull request closed without merging**
